spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 320MB
      max-request-size: 320MB
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#  http:
#    multipart:
#      location: E:/img
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/public/, file:${spring.http.multipart.location}

#取消mybatis自动映射自动转化大小写
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false

logging:
  level:
    com.framework.quickly.mapper: debug

myData:
  imageDisc: 'E:/img'
  imageAccess: 'http://localhost:8800/image/'

server:
  port: 8800




